name: Release

on:
  push:
    branches:
      - dev
      - main

jobs:
  eavfw_test:
    uses: ./.github/workflows/testeavfw.yml

  release:
    name: Releasing
    runs-on: windows-latest
    needs:
      - eavfw_test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json
          
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows

      - name: Add plugin for executing bash commands
        run: npm install @semantic-release/exec -D
        working-directory: ./.github/workflows

      - name: Dry Run Semantic to get next Version nummber
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: thygesteffensen
          GIT_AUTHOR_EMAIL: thygesteffensen@users.noreply.github.com
        run: |
          echo "RELEASE_VERSION=$((npx semantic-release --dry-run).Where({ $_ -like '*Release note*' }) | Out-String | Select-String '[0-9]+\.[0-9]+\.[0-9]+([-][a-zA-z]+[.][0-9]*)?' | % { $_.Matches } | % { $_.Value })" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Print release verison
        run: echo ${env:RELEASE_VERSION}

      - name: Cleaning
        run: dotnet clean

      # - name: Restore NuGet packages
      #   run: dotnet restore ExpressionEngine.sln

      - name: Packaging
        run: dotnet pack -c Release -p:PackageVersion=${env:RELEASE_VERSION} -o ./artifacts
        if: ${{ env.RELEASE_VERSION }}

      - name: Release to GitHub and NuGet
        working-directory: .\\.github\\workflows
        env:
          CI_NUGET_API_KEY: ${{ secrets.CI_NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: thygesteffensen
          GIT_AUTHOR_EMAIL: 31892312+thygesteffensen@users.noreply.github.com
        run: npx semantic-release
