name: Release

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: windows-latest
    name: Testing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install EAVFW template
        run: dotnet new --install .\templates\EAVFW\

      - name: install EAVFW NextJS template
        run: dotnet new --install .\templates\EAVFW.NextJS\

      - name: create directory for test project
        run: mkdir EAV001
        working-directory: "./../"

      - name: create test project from template
        run: dotnet new eavfw --projectPrefix "GithubTestOrg" --mainAppReplace "GithubTestApp" --databaseName "GithubTestDB  --skipExtensions "true" --skipRestore "true" --skipRestoreNoCache "true" --withManifestGeneration "false""
        working-directory: "./../EAV001"
        
      - name: create test web portal from template
        run: npm run eav-nextjs
        working-directory: "./../EAV001"

      - name: run npm install --force
        run: npm install --force
        working-directory: "./../EAV001"

      - name: generate manifest
        run: npm run gm
        working-directory: "./../EAV001"

      - name: build and export web portal
        run: npm run build
        working-directory: "./../EAV001/apps/GithubTestOrg.GithubTestApp"


        # TODO: 
        #-Add testing with msbuild
        # STEPS:
        # -Run ```dotnet new --install .\templates\EAVFW\```
        # -Run ```dotnet new --install .\templates\EAVFW.NextJS\```
        # -Create test directory
        # -Run ```dotnet new eavfw --projectPrefix "MyOrg001" --mainAppReplace "MyEAVTestApp001" --databaseName "MyEAVTestAppDatabase001"```
        # -Rebuild solution twice
        # -Build solution twice
        # -Run ```npm install --force```
        # -From app project as WD, Run ```npm run build```




    

  release:
    name: Releasing
    runs-on: windows-latest
    needs:
       - test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows

      - name: Add plugin for executing bash commands
        run: npm install @semantic-release/exec -D
        working-directory: ./.github/workflows

      - name: Dry Run Semantic to get next Version nummber
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: thygesteffensen
          GIT_AUTHOR_EMAIL: thygesteffensen@users.noreply.github.com
        run: |
          echo "RELEASE_VERSION=$((npx semantic-release --dry-run).Where({ $_ -like '*Release note*' }) | Out-String | Select-String '[0-9]+\.[0-9]+\.[0-9]+([-][a-zA-z]+[.][0-9]*)?' | % { $_.Matches } | % { $_.Value })" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Print release verison
        run: echo ${env:RELEASE_VERSION}

      - name: Cleaning
        run: dotnet clean

      # - name: Restore NuGet packages
      #   run: dotnet restore ExpressionEngine.sln

      - name: Packaging
        run: dotnet pack -c Release -p:PackageVersion=${env:RELEASE_VERSION} -o ./artifacts
        if: ${{ env.RELEASE_VERSION }}

      - name: Release to GitHub and NuGet
        working-directory: .\\.github\\workflows
        env:
          CI_NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: thygesteffensen
          GIT_AUTHOR_EMAIL: 31892312+thygesteffensen@users.noreply.github.com
        run: npx semantic-release
